### PR TITLE
src: Increase requests per second for all sources

### PR DESCRIPTION
**Pull request by niclimcy**
Not sure why this was so low from before

### CODE REVIEW

**Comment by xOnlyFadi** [comment]
Change version number for sources to and why it’s low because it used an old template from 0.6 when i started doing sources for pb

**Comment by xOnlyFadi** [comment]
Ready to be merged?

**Comment by niclimcy** [comment]
> Ready to be merged?

Yes, I'll take a look at other things over the weekend instead

**Comment by xOnlyFadi** [comment]
Thanks for the help

**Pull request merged**
