### PR TITLE
Various fixes / VyvyManga

### PR DESCRIPTION
**Pull request by niclimcy**

### CODE REVIEW

**Comment by xOnlyFadi** [comment]
why html to text removed it's helpful to remove html tags?

**Comment by niclimcy** [comment]
> why html to text removed it's helpful to remove html tags?

The places they are currently used are in json which don’t have html, I would hope so

**Comment by xOnlyFadi** [comment]
> > why html to text removed it's helpful to remove html tags?
> 
> The places they are currently used are in json which don’t have html, I would hope so

I added this on both sources because most of old mangas use html i tried removing using a regex did not work this package work perfectly

**Comment by niclimcy** [comment]
> > > why html to text removed it's helpful to remove html tags?
> > 
> > 
> > The places they are currently used are in json which don’t have html, I would hope so
> 
> I added this on both sources because most of old mangas use html i tried removing using a regex did not work this package work perfectly

The last 2 places that have it are ComicK and Voyce, both use apis to get data which returns some form of json, so I don’t think there will be any html there lol

**Comment by xOnlyFadi** [comment]
> > > > why html to text removed it's helpful to remove html tags?
> > > 
> > > 
> > > The places they are currently used are in json which don’t have html, I would hope so
> > 
> > 
> > I added this on both sources because most of old mangas use html i tried removing using a regex did not work this package work perfectly
> 
> The last 2 places that have it are ComicK and Voyce, both use apis to get data which returns some form of json, so I don’t think there will be any html there lol

there is they put in the api the html tags voyceme or comick
VoyceME
```json
{
            "description": "&#x3C;p&#x3E;When you are chosen by the fates to become an Arcana you will find yourself thrust into a world ruled by magic and strength. Arcana can harness the will of the Tarot Spirit that chose them to change the world for better or worse.&#x3C;/p&#x3E;",
}
```
Comick
```json
    "desc": "A player who can fight creatures from the wonders of another world. The main protagonist, Ariake Subaru, was bullied and was chosen as a player of the “Rainbow” rank, which is neither gold, silver, nor copper. He acquired the skill to freely manipulate blood, and his life and position changed completely. As he continues to fight every day, he gradually earns the title as a “Savior” who will save the world.\n\nA modern battle fantasy from the up-and-coming production team, “Studio No.9”!",
    "parsed": "<p>A player who can fight creatures from the wonders of another world. The main protagonist, Ariake Subaru, was bullied and was chosen as a player of the “Rainbow” rank, which is neither gold, silver, nor copper. He acquired the skill to freely manipulate blood, and his life and position changed completely. As he continues to fight every day, he gradually earns the title as a “Savior” who will save the world.</p>\n<p>A modern battle fantasy from the up-and-coming production team, “Studio No.9”!</p>\n",
```
some will have the parsed version in desc

**Comment by niclimcy** [comment]
> > > > > why html to text removed it's helpful to remove html tags?
> > > > 
> > > > 
> > > > The places they are currently used are in json which don’t have html, I would hope so
> > > 
> > > 
> > > I added this on both sources because most of old mangas use html i tried removing using a regex did not work this package work perfectly
> > 
> > 
> > The last 2 places that have it are ComicK and Voyce, both use apis to get data which returns some form of json, so I don’t think there will be any html there lol
> 
> there is they put in the api the html tags voyceme or comick VoyceME
> 
> ```json
> {
>             "description": "&#x3C;p&#x3E;When you are chosen by the fates to become an Arcana you will find yourself thrust into a world ruled by magic and strength. Arcana can harness the will of the Tarot Spirit that chose them to change the world for better or worse.&#x3C;/p&#x3E;",
> }
> ```
> 
> Comick
> 
> ```json
>     "desc": "A player who can fight creatures from the wonders of another world. The main protagonist, Ariake Subaru, was bullied and was chosen as a player of the “Rainbow” rank, which is neither gold, silver, nor copper. He acquired the skill to freely manipulate blood, and his life and position changed completely. As he continues to fight every day, he gradually earns the title as a “Savior” who will save the world.\n\nA modern battle fantasy from the up-and-coming production team, “Studio No.9”!",
>     "parsed": "<p>A player who can fight creatures from the wonders of another world. The main protagonist, Ariake Subaru, was bullied and was chosen as a player of the “Rainbow” rank, which is neither gold, silver, nor copper. He acquired the skill to freely manipulate blood, and his life and position changed completely. As he continues to fight every day, he gradually earns the title as a “Savior” who will save the world.</p>\n<p>A modern battle fantasy from the up-and-coming production team, “Studio No.9”!</p>\n",
> ```
> 
> some will have the parsed version in desc

Oh oof ok, let me see what I can do

**Comment by niclimcy** [comment]
Ok ready to merge

**Comment by xOnlyFadi** [comment]
ready to be merged?

**Comment by niclimcy** [comment]
For now yes, I am still trying to fix the broken-ish settings for ComicK but that will take a bit more time. Will make another pull request for that.

**Comment by xOnlyFadi** [comment]
revert the old request with pages it's needed for 1000+ chapters

**Comment by niclimcy** [comment]
> revert the old request with pages it's needed for 1000+ chapters

The way I am fetching now is a bit different, I find the total number of chapters in the first request and then query using the limit parameter to fetch all chapters in the second query. That’s why the page function is no longer needed. This will limit the amount of times we fetch from the API

**Comment by xOnlyFadi** [comment]
ready be merged?

**Comment by niclimcy** [comment]
Yes

**Pull request merged**
